#!/bin/bash
/home/gcarreno/fpcupdeluxe/fpc/bin/x86_64-linux/fpdoc \
    --package=lazqBitTorrentWebUI \
    --output=/home/gcarreno/Programming/laz-qBitTorrent-WebUI/docs/html \
    --format=html \
    --descr=/home/gcarreno/Programming/laz-qBitTorrent-WebUI/docs/xml/qbittorrentwebui.xml \
    --descr=/home/gcarreno/Programming/laz-qBitTorrent-WebUI/docs/xml/qbtorrents.xml \
    --input=/home/gcarreno/Programming/laz-qBitTorrent-WebUI/src/qBitTorrentWebUI.pas \
    --input=/home/gcarreno/Programming/laz-qBitTorrent-WebUI/src/qBTorrents.pas
