name: build-test

on:
  pull_request:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - builds/runBuilds
    branches:
      - master
      - releases/*
      - devel

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest,windows-latest,macos-latest]
        lazarus-versions: [stable, 2.0.10]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.2
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        include-packages: "Synapse 40.1"
    - name: Build the Example App
      run: |
        lazbuild --add-package-link "package/lazqbittorrentwebui.lpk";
        lazbuild "example/Lazarus/project1.lpi";
    - name: Build the Test App
      run: lazbuild "tests/lazqbtest.lpi";
    - name: Run the Test App
      run: bin/lazqbtest "--all" "--format=plain";
